Feature/haechan45th initail setting
wecode-bootcamp-korea/45-backend-westagram-1 pull request #1
Opened 2023-04-17 09:59 UTC by haechan02

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [1. ] 기능 추가
-  initializing

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Initializing the folder with npm & git
- Server return 'pong' from GET http://127.0.0.1:8000/ping

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 폴더 생성후 서버 생성 및 /ping 사용을 통해 정상작동 확인.

<br />

## :: 테스트 결과 이미지

1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![Screenshot 2023-04-17 at 6 58 20 PM](https://user-images.githubusercontent.com/120645757/232451949-54440c1e-aa68-4d9e-b801-d2344b5606f6.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="863" alt="Screenshot 2023-04-17 at 6 55 05 PM" src="https://user-images.githubusercontent.com/120645757/232451960-f2df9549-9b8a-4e92-bed7-7204583fe501.png">

5. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-17 10:11 UTC, kyeongraekim commented
- PR 템플릿 title 을, 슬랙 공지사항으로 안내해드린 문구에 맞게 수정해주세요!

2023-04-17 10:31 UTC, kyeongraekim requested changes

2023-04-17 10:31 UTC, kyeongraekim commented on haechan45th/app.js
> +const app = express();
- port의 변수는 외부 써드파티 패키지를 담아노은 다른 영역과는 다소 다른 의미의 변수이네요!
- 해당 port는 환경 변수를 불러오는 다른 영역과 가까운 위치에서 호출해주세요!

2023-04-17 10:31 UTC, kyeongraekim commented on haechan45th/package.json
> +    "typeorm": "^0.3.15"
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql2, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.

2023-04-17 10:31 UTC, kyeongraekim commented on package.json
> +{
- 해당 파일은 불필요한 package.json 처럼 보여지네요! 한 프로젝트에 하나의 package.json이 유지될 수 있도록 유의해주세요!

2023-04-17 14:07 UTC, haechan02 commented on package.json
> +{
넵 감사합니다!

2023-04-17 14:07 UTC, haechan02 commented on haechan45th/package.json
> +    "typeorm": "^0.3.15"
넵 devDependecies 로 보내었습니다!

2023-04-17 14:08 UTC, haechan02 commented on haechan45th/app.js
> +const app = express();
넵 app.js 안에 port 8000으로 바꿨습니다

2023-04-18 01:15 UTC, kyeongraekim requested changes

2023-04-18 01:15 UTC, kyeongraekim commented on haechan45th/app.js
> +    res.status(201).json({message:"userCreated"})
- 현재 초기환경세팅과 무관한 파일 내역이 보이네요! 깃헙에 대한 명확한 브랜치 구분 관리를 위해서 해당 내역은 삭제해주시고, 초기세팅과 관련된 내용만 푸시되어 머지될 수 있게 수정해주세요!

2023-04-18 08:37 UTC, merged

2023-04-18 08:37 UTC, Jon9Beom commented
LGTM 👍