[오진석] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/45-backend-westagram-1 pull request #2
Opened 2023-04-17 10:05 UTC by jinss5

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- express 초기 환경 세팅

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express 설치 / 적용
- nodemon 설치 / 적용
- cors 설치 / 적용
- dotenv 설치 / 환경 변수 적용
- morgan 설치 / 적용
- TypeORM 설치 및 적용
- dbConnection 정상 작동 확인

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="998" alt="Screen Shot 2023-04-17 at 6 52 32 PM" src="https://user-images.githubusercontent.com/62521403/232452503-38d79660-3971-4d26-9080-77bab568163f.png">
<br />

## :: 기타 질문 및 특이 사항

-

2023-04-17 10:28 UTC, kyeongraekim requested changes

2023-04-17 10:28 UTC, kyeongraekim commented on jinseok/app.js
> +const { DataSource } = require('typeorm');
```suggestion
//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();
```

2023-04-17 10:28 UTC, kyeongraekim commented on jinseok/app.js
> +const { DataSource } = require('typeorm');
- 위 내용과 같이 써드파티 패키지, 커스텀 패키지의 기능적 영역을 라인브레이킹을 통해서 구분지어주세요!
- 위에 적힌 주석은 참고용으로 남겨둔 것임으로, 수정에 반영하실 때에는 삭제해주세요!

2023-04-17 10:28 UTC, kyeongraekim commented on jinseok/package.json
> +    "nodemon": "^2.0.22",
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql2, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.

2023-04-17 10:28 UTC, kyeongraekim commented on jinseok/app.js
> +  console.log('server listening on port 3000');
- port 번호를 port 변수에 담아온 환경변수가 반영될 수 있게 문자열 하드코딩을 수정해주세요!

2023-04-18 08:12 UTC, Jon9Beom reviewed
.env.sample 파일 추가해주세요!

2023-04-18 08:12 UTC, Jon9Beom commented on jinseok/app.js
> +});
- 추가로 `dataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
- typeorm 공식문서에서 initialize() 하는 부분을 참고하여 수정해주세요!

2023-04-18 08:12 UTC, Jon9Beom commented on jinseok/package.json
> +    "morgan": "^1.10.0",
```suggestion
```
npm uninstall 해주시고, dev dependencies로 재설치 해주세요!

2023-04-18 09:33 UTC, Jon9Beom commented on jinseok/.env.sample
> +DATABASE_URL="mysql://username:password@127.0.0.1:3306/myDB"
```suggestion
PORT = YOUR PORT NUMBER SHOULD BE HERE

DB_CONNECTION=db_type
DB_HOST=db_host
DB_USERNAME=username
DB_PASSWORD=password
DB_DATABASE=myDB
DB_PORT=db_port
DB_LOGGING=true / false

DATABASE_URL="rdbms://username:password@localhost:db_port/myDB"
```

2023-04-18 09:38 UTC, merged

2023-04-18 09:38 UTC, Jon9Beom commented
LGTM 👍